### ISSUE TITLE
How to use this lib?

### ISSUE THREAD

**Issue by oscarfh** [micronaut-projects/micronaut-jmx#2]
Hi,
I am trying to troubleshoot a blocker issue we have and I was hoping to connect using JMX to get some data about our application, but I cannot understand how to use this lib.
I added it as a dependency and expected that I could configure some port or so so I can connect, but this does not seem to be the case.

Could someone please direct me to an example or tutorial?

**Comment by jameskleeh** [comment]
@oscarfh There really isn't anything beyond the documentation https://micronaut-projects.github.io/micronaut-jmx/latest/guide/. If you have some specific questions, please ask on Gitter
